import Foundation

/// Explicit UI localization. User prompts, paths, model IDs and records are not translated.
enum AppLanguage {
    static var code: String {
        let saved = UserDefaults.standard.string(forKey: "app.language")
        if let saved, ["ko", "en"].contains(saved) { return saved }
        return Locale.preferredLanguages.first?.hasPrefix("ko") == true ? "ko" : "en"
    }
    static let english: [String: String] = [
        "인증 정보·쿼리가 없는 HTTPS API 기본 주소를 입력하세요.": "Enter an HTTPS API base URL without credentials or a query.",
        "Keychain에서 API 키를 읽거나 저장하지 못했습니다. 키를 다시 저장하세요.": "Unable to read or save the API key in Keychain. Save the key again.",
        "API 응답이 지원 형식과 다릅니다. 제공자의 모델·출력 형식을 확인하세요.": "Unsupported API response. Check the provider's model and output format.",
        "API 오류 HTTP {0}. 인증·잔액·모델 지원을 확인하세요.": "API error HTTP {0}. Check authentication, balance and model support.",
        "서비스의 영상 생성 작업이 실패했습니다.": "The service failed to generate the video.",
        "영상 작업 대기 시간이 초과되었습니다. 원격 작업 ID를 확인하세요.": "Video request timed out. Check the remote job ID.",
        "영상 생성: {0} · {1}%": "Video generation: {0} · {1}%",
        "온라인 API 요청 중": "Requesting online API",
        "생성 완료 · 검토 전 · {0}초": "Generated · awaiting review · {0}s",
        "대기를 중단했습니다. 원격 서비스의 생성·과금이 중단된 것은 아닙니다. 작업 ID를 확인하세요.": "Stopped waiting. Remote generation and billing may continue. Check the job ID.",
        "{0} · 선택형 API": "{0} · Optional API",
        "요청을 선택한 서비스에 전송합니다. 사용료는 해당 서비스 계정에 적용됩니다. 로컬 모드로 자동 전환하거나 로컬 입력을 자동 업로드하지 않습니다.": "Your request goes to the selected service and is billed to that account. Local inputs are never uploaded automatically.",
        "OpenRouter · OpenAI 호환 API 연결": "OpenRouter · OpenAI-compatible API",
        "HTTPS API 기본 주소": "HTTPS API base URL",
        "제공자가 지원하는 모델 ID": "Supported model ID",
        "API 키 (Keychain 저장)": "API key (stored in Keychain)",
        "키 저장": "Save key",
        "이 API 주소의 키를 Keychain에 저장했습니다.": "Saved the key for this API address in Keychain.",
        "저장 키 삭제": "Delete saved key",
        "저장 키 삭제 요청 완료": "Key deletion requested",
        "규격: /audio/speech · WAV": "Format: /audio/speech · WAV",
        "규격: /images/generations · base64 이미지 응답": "Format: /images/generations · base64 image response",
        "규격: /videos · 생성 요청 / 상태 조회 / MP4 다운로드": "Format: /videos · create / poll / download MP4",
        "목소리 ID": "Voice ID",
        "크기 (예: 1024x1024 / 영상 720x1280)": "Size (e.g. 1024x1024 / video 720x1280)",
        "초": "Seconds",
        "4초": "4 seconds",
        "8초": "8 seconds",
        "12초": "12 seconds",
        "온라인 API로 생성": "Generate with online API",
        "대기 중단": "Stop waiting",
        "원본 보기": "View original",
        "기록 폴더 열기": "Open records folder",
        "{0}에 프롬프트를 보내 {1}로 생성할까요? 서비스 사용료가 발생할 수 있습니다.": "Send the prompt to {0} and generate with {1}? Service charges may apply.",
        "전송하고 생성": "Send and generate",
        "취소": "Cancel",
        "이전 작업 확인 실패: ": "Unable to check previous jobs: ",
        "생성하지 못했습니다. 결과 폴더의 stderr.log를 확인하세요.": "Generation failed. Check stderr.log in the output folder.",
        "전하고 싶은 말을 적고, 목소리로 들어보세요.": "Write what you want to say, then hear it aloud.",
        "주제와 구도, 빛과 분위기를 함께 설명해보세요.": "Describe your subject, composition, lighting and mood.",
        "한 장면의 움직임과 대사, 소리를 구체적으로 적어보세요.": "Describe the motion, dialogue and sound of one scene.",
        "찾아보기": "Browse",
        "생성 모델을 연결해주세요": "Connect a generation model",
        "접기": "Collapse",
        "연결 설정": "Connection settings",
        "실행 파일": "Executable",
        "로컬 모델 폴더": "Local model folder",
        "경로 지정 후 생성 시 모델을 불러옵니다. 가중치와 실행 도구는 별도로 준비해야 합니다.": "The model loads when generation starts. Prepare the weights and runtime separately.",
        "읽을 내용": "Text to read",
        "장면 설명": "Scene description",
        "{0}자": "{0} characters",
        "예: 안녕하세요. 오늘의 업무를 함께 시작해볼까요?": "Example: Hello. Shall we get started on today's work together?",
        "예: 아침 햇살이 비치는 책상 위의 은색 컴퓨터. 따뜻한 분위기, 정돈된 구도…": "Example: A silver computer on a desk in morning sunlight. Warm light, a clean composition…",
        "한국어": "Korean",
        "화자": "Speaker",
        "{0}스텝": "{0} steps",
        "{0}프레임 요청": "{0} frames requested",
        "시작 이미지 추가": "Add starting image",
        "변경": "Change",
        "제거": "Remove",
        "크기와 생성 옵션": "Size and generation options",
        "가로": "Width",
        "세로": "Height",
        "스텝": "Steps",
        "시드": "Seed",
        "프레임": "Frames",
        "가로·세로는 32의 배수입니다. 설정을 바꾸면 속도와 품질이 달라지며, 영상 길이는 실제 결과에서 확인합니다.": "Width and height must be multiples of 32. Settings affect speed and quality. Check the actual output duration.",
        "먼저 설정을 확인한 뒤 생성합니다.": "Review the settings before generating.",
        "작업 준비": "Prepare job",
        "생성 중 · 다른 화면으로 이동해도 계속됩니다.": "Generating · work continues when you change screens.",
        "경과 {0}초 · 모델 준비 포함": "Elapsed {0}s · includes model preparation",
        "중단": "Stop",
        "작업 결과": "Job result",
        "확인한 입력으로 생성합니다. 아래 작성란을 수정했다면 작업 준비를 다시 눌러주세요.": "Generation uses the reviewed input. If you changed the form, prepare the job again.",
        "이 설정으로 생성": "Generate with these settings",
        "같은 설정으로 새 작업": "New job with same settings",
        "Finder에서 보기": "Show in Finder",
        "원본 열기": "Open original",
        "전체 실행 %.2f초": "Total runtime %.2fs",
        "설정과 실행 기록": "Settings and execution records",
        "파일 생성 완료. 내용과 품질을 확인한 뒤 사용하세요.": "File generated. Review its content and quality before use.",
        "음성 만들기": "Create speech",
        "이미지 만들기": "Create images",
        "영상 만들기": "Create video",
        "MiniMax H3 Turbo8 FL2VA · 8스텝 / h3.c": "MiniMax H3 Turbo8 FL2VA · 8 steps / h3.c",
        "실행 가능한 로컬 CLI 파일을 선택하세요.": "Select an executable local CLI file.",
        "이미 준비된 로컬 모델 폴더를 선택하세요. 모델 ID로 다운로드하지 않습니다.": "Select an existing local model folder. Model IDs are not downloaded here.",
        "생성할 내용을 입력하세요.": "Enter content to generate.",
        "크기는 64~2048의 32 배수, 스텝은 1~100, 프레임은 1~401, 시드는 0 이상이어야 합니다.": "Dimensions must be multiples of 32 from 64–2048; steps 1–100; frames 1–401; seed 0 or greater.",
        "읽을 수 있는 시작 이미지 파일을 선택하세요.": "Select a readable starting image file.",
        "실행 기록이며 모델 호환성·품질·성능 검증을 의미하지 않습니다.": "Execution record only; not a certification of compatibility, quality or performance.",
        "앱 재시작 시 완료 기록이 없는 작업입니다. 결과와 로그를 확인한 뒤 새 작업으로 다시 시도하세요.": "No completion record was found after restart. Check outputs and logs before preparing a new job.",
        "설정 확인 대기": "Awaiting settings review",
        "실행 중 / 기록 확인": "Running / check records",
        "생성 완료 · 검토 전": "Generated · awaiting review",
        "중단된 작업 · 확인 후 재시도": "Interrupted · review before retry",
        "중단됨": "Cancelled",
        "실행 실패": "Execution failed",
        "모델의 도구 요청 형식이 올바르지 않습니다. 모델을 바꾸거나 작업을 구체적으로 적어주세요.": "Invalid model tool request. Try another model or a more specific task.",
        "선택한 폴더의 일반 텍스트 파일만 사용할 수 있습니다. 숨김 파일, 상위 경로, 심볼릭 링크는 허용하지 않습니다.": "Only regular text files in the selected folder are allowed. Hidden files, parent paths and symlinks are blocked.",
        "CLI 실행 파일을 찾지 못했습니다. 설치 및 로그인 후 실행 파일을 선택하세요.": "CLI executable not found. Install, sign in and select the executable.",
        "로컬 서버에 연결하고 모델을 선택하세요.": "Connect a local server and select a model.",
        "작업의 8단계 한도에 도달했습니다. 결과를 확인하고 더 작은 작업으로 이어가세요.": "Reached the 8-step limit. Review the result and continue with a smaller task.",
        " 생성 완료": " created",
        "작업 폴더를 선택하세요.": "Select a workspace folder.",
        "{0}. {1} 계획 중": "{0}. {1} planning",
        "도구: {0} {1}": "Tool: {0} {1}",
        "사용자가 이 도구 실행을 거절했습니다. 같은 작업을 우회하거나 반복하지 마세요.": "The user declined this tool. Do not retry or bypass the decision.",
        "도구 실행 실패: ": "Tool failed: ",
        "작업을 중단했습니다. 실행 기록은 보관됩니다.": "Task stopped. Execution records are retained.",
        "{0} 실행 실패 ({1}). 설치 버전·로그인·사용 한도를 확인하세요. 기록 폴더의 stderr.log에서 원인을 확인할 수 있습니다.": "{0} failed ({1}). Check the installed version, login and usage limits. See stderr.log in the records folder.",
        "로컬 주소만 사용할 수 있습니다. 예: http://127.0.0.1:1234/v1": "Only local addresses are allowed. Example: http://127.0.0.1:1234/v1",
        "로컬 서버 응답 오류 (HTTP {0}). 서버의 모델·인증 설정을 확인하세요.": "Local server error (HTTP {0}). Check the server's model and authentication settings.",
        "응답 연결이 완료 전에 끊겼습니다. 부분 응답을 확인하고 다시 요청하세요.": "The connection ended before completion. Review the partial response and try again.",
        "모델이 응답 내용을 반환하지 않았습니다.": "The model returned no response content.",
        "AI에게 작업을 맡기세요": "Let AI work with you",
        "내 Mac의 AI가 자료를 읽고, 문서를 만들고, 생성 도구를 준비합니다.": "Your Mac's AI reads materials, creates documents and prepares generation tools.",
        "작업 브레인": "Task brain",
        "로컬 AI · 기본": "Local AI · Default",
        "Codex · 온라인": "Codex · Online",
        "Claude · 온라인": "Claude · Online",
        "로컬 브레인 연결": "Local brain connection",
        "선택한 온라인 브레인": "Selected online brain",
        "로컬 서버 주소": "Local server URL",
        "모델 찾기": "Find models",
        "모델": "Model",
        "설치된 로컬 모델을 사용합니다. H3는 외부 API로 자동 전환하지 않습니다. 오프라인 실행에는 로컬 전용 서버 설정과 준비된 모델이 필요합니다.": "Uses installed local models. H3 never switches to an external API automatically. Offline work requires a local-only server and prepared models.",
        "CLI 실행 파일": "CLI executable",
        "모델 ID (비우면 CLI 기본 모델)": "Model ID (leave empty for CLI default)",
        "인터넷·해당 서비스 로그인이 필요합니다. 요청과 선택한 도구가 읽은 자료는 해당 서비스로 전송됩니다. H3 도구 실행은 아래 승인 흐름을 따릅니다.": "Internet and service login are required. Requests and files read by approved tools go to that service. H3 tools follow the approval flow below.",
        "공식 설치·로그인 안내 ↗": "Official installation and login guide ↗",
        "이 작업에 사용할 폴더": "Workspace for this task",
        "폴더 선택": "Choose folder",
        "사용 도구: 텍스트 목록·읽기 / 새 문서 쓰기 / 음성·이미지·영상 작업 준비": "Tools: list/read text · create new documents · prepare speech, image or video jobs",
        "자료를 읽고 기획하기": "Read and plan",
        "폴더의 자료를 먼저 확인하고 핵심 내용을 읽은 뒤, 30초 소개 영상 기획안을 새로운 teaser-plan.md 문서로 만들어주세요.": "Review the files in this folder, read the key materials, then create a new teaser-plan.md with a plan for a 30-second introduction video.",
        "작업 시작": "Start task",
        "실행 전 확인": "Review before execution",
        "새 문서: {0}": "New document: {0}",
        "{0} 생성 작업 준비": "Prepare {0} generation job",
        "승인": "Approve",
        "거절": "Decline",
        "승인하면 작업을 준비합니다. 실제 생성은 해당 생성 화면에서 설정을 확인한 뒤 시작합니다.": "Approval prepares the job. Review the settings on the generation screen before starting generation.",
        "작업 과정 · {0}개 이벤트": "Activity · {0} events",
        "음성 작업 보기": "View speech job",
        "이미지 작업 보기": "View image job",
        "영상 작업 보기": "View video job",
        "기록 폴더": "Records folder",
        "Ollama를 실행한 뒤 목록을 새로고침하세요.": "Start Ollama and refresh the list.",
        "설치된 모델 {0}개 · {1} 확인": "{0} installed models · checked {1}",
        "Ollama 연결 확인: ": "Check Ollama connection: ",
        "로컬 모델의 정확한 이름:태그를 입력하세요.": "Enter the exact local model name:tag.",
        "{0} 확인 중…": "Checking {0}…",
        "다운로드 중": "Downloading",
        "{0} 다운로드 / 태그 업데이트 완료": "{0} download / tag update complete",
        "다운로드 연결을 중단했습니다. 목록을 새로고침하여 상태를 확인하세요.": "Download connection stopped. Refresh the list to check the state.",
        "모델 라이브러리": "Model library",
        "모델을 고르고, 최신 태그를 받고, 바로 대화에 연결하세요.": "Choose installed models, download updated tags and connect to chat.",
        "설치 모델 검색": "Search installed models",
        "목록 새로고침": "Refresh list",
        "최신 모델 탐색 ↗": "Explore latest models ↗",
        "다운로드 · 업데이트": "Download · Update",
        "Ollama 공식 라이브러리에서 모델 이름:태그를 복사하세요. 같은 태그를 다시 받으면 변경된 버전을 확인합니다.": "Copy a model name:tag from Ollama's official library. Pulling the same tag checks for a newer version.",
        "예: qwen3.8:27b": "Example: qwen3.8:27b",
        "다운로드 / 업데이트": "Download / Update",
        "모델 크기와 라이선스를 공식 페이지에서 확인하세요. 파일 크기보다 실행 메모리가 더 필요합니다. 이 화면은 Ollama 로컬 모델을 관리하며, 음성·이미지·H3 모델은 모델과 연결에서 설정합니다.": "Check model size and license on the official page. Runtime memory exceeds file size. This library manages local Ollama models; configure speech, image and H3 models in their generation screens.",
        "현재 레이어 다운로드 진행률": "Current layer download progress",
        "대화에 사용": "Use in chat",
        "버전 {0} · 변경 {1}": "Version {0} · modified {1}",
        "이 태그 업데이트": "Update this tag",
        "Ollama 설치 및 연결": "Install and connect Ollama",
        "Ollama for Mac 설치 ↗": "Install Ollama for Mac ↗",
        "로컬 Ollama API 주소 (/v1)": "Local Ollama API URL (/v1)",
        "{0}을 다운로드하거나 업데이트할까요? 저장 공간과 네트워크를 사용하며, 같은 태그의 모델이 갱신될 수 있습니다.": "Download or update {0}? This uses storage and network. An existing model with the same tag may be updated.",
        "저장한 대화를 읽지 못했습니다. 원본 파일은 보존됩니다. ": "Unable to read the saved conversation. The original file is preserved. ",
        "대화 저장 실패: ": "Unable to save conversation: ",
        "서버에 모델이 없습니다. 실행 도구에서 로컬 모델을 준비한 뒤 다시 연결하세요.": "No models on the server. Prepare a local model in your runtime, then reconnect.",
        "연결하지 못했습니다. 로컬 서버가 실행 중인지 확인하세요.\n": "Unable to connect. Check that the local server is running.\n",
        "응답을 중단했습니다. 입력은 복원했으며 부분 응답은 아래에 표시됩니다.": "Response stopped. Your input was restored; the partial response is shown below.",
        "H3 · AI 컴퓨터": "H3 · AI Computer",
        "홈": "Home",
        "대화": "Chat",
        "음성": "Voice",
        "이미지": "Images",
        "영상": "Video",
        "작업 보관함": "Job library",
        "모델과 연결": "Models & connections",
        "AI 에이전트": "AI agent",
        "콘텐츠 생성 중": "Generating content",
        "답변 준비 중": "Preparing response",
        "대화 연결됨": "Chat connected",
        "로컬 워크스페이스": "Local workspace",
        "실행 위치": "Execution location",
        "내 Mac · 설치 모델": "My Mac · Installed model",
        "온라인 API · 선택": "Online API · Optional",
        "콘텐츠 생성에 메모리를 사용하려면 대화 모델을 잠시 내려주세요.": "Unload the chat model to free memory for content generation.",
        "대화 모델 내려놓기": "Unload chat model",
        "로컬 {0} 작업 준비 완료. 실제 생성 전 사용자가 생성 화면에서 설정을 확인해야 합니다.": "Local {0} job prepared. Review settings in the generation screen before starting.",
        "AI 컴퓨터": "AI Computer",
        "내 Mac에서 실행": "Runs on your Mac",
        "당신의 일에 집중하는 AI.": "AI focused on your work.",
        "생각을 정리하고,\n만들고 싶은 것을 만드세요.": "Think it through.\nBring your ideas to life.",
        "대화에서 목소리, 이미지, 영상까지. H3가 내 Mac의 AI를 하나의 작업 공간으로 연결합니다.": "From chat to voice, images and video. H3 connects your Mac's AI in one workspace.",
        "시작 준비 · 3단계": "Get started · 3 steps",
        "1. Mac 확인 · {0} GB 통합 메모리": "1. Mac ready · {0} GB unified memory",
        "2. 대화 모델 연결 완료": "2. Chat model connected",
        "2. 설치된 모델 또는 로컬 서버 연결": "2. Connect an installed model or local server",
        "3. 첫 콘텐츠를 만들고 보관함에서 확인": "3. Create your first content and check the library",
        "3. 작업 보관함 준비 완료": "3. Job library ready",
        "대화 이어가기": "Continue chat",
        "모델 연결 시작": "Connect a model",
        "AI에게 작업 맡기기": "Let AI handle a task",
        "내 자료를 읽고, 기획하고, 로컬 생성 도구를 준비하는 에이전트.": "An agent that reads your files, plans work and prepares local creation tools.",
        "에이전트 시작": "Start agent",
        "내 모델 라이브러리": "Your model library",
        "설치 모델을 고르고, 최신 태그를 다운로드하고, 바로 연결하세요.": "Choose installed models, download updated tags and connect right away.",
        "모델 둘러보기": "Explore models",
        "함께 생각하는 대화": "Think together",
        "아이디어를 정리하고, 문서를 다듬고, 다음 할 일을 찾아보세요.": "Organize ideas, refine documents and work out what comes next.",
        "대화 시작": "Start chatting",
        "문장을 목소리로": "Words into voice",
        "안내 멘트와 내레이션을 만들고, 바로 들어보세요.": "Create announcements and narration, then listen right away.",
        "아이디어를 이미지로": "Ideas into images",
        "제품 사진부터 새로운 장면까지, 원하는 모습을 구체화하세요.": "From product photos to new scenes, give your ideas a visual form.",
        "장면에 움직임을": "Bring scenes to life",
        "첫 이미지와 장면 설명으로 소리 있는 영상을 만들어보세요.": "Create video with sound from a starting image and scene description.",
        "{0} GB 메모리": "{0} GB memory",
        "모델과 연결 관리": "Manage models & connections",
        "최근 작업": "Recent jobs",
        "전체 보기": "View all",
        "모델을 연결하고 첫 결과를 만들어보세요. 대화와 생성 기록은 이 Mac에 보관됩니다.": "Connect a model and create your first result. Conversations and generation records stay on this Mac.",
        "내 AI를 연결하세요": "Connect your AI",
        "직접 실행하거나, 이미 사용하는 로컬 AI 서버에 연결할 수 있습니다.": "Start a model yourself or connect a local AI server you already use.",
        "H3에서 대화 모델 실행": "Run a chat model in H3",
        "설치된 mlx_vlm.server와 로컬 모델 폴더를 선택하세요.": "Select the installed mlx_vlm.server executable and local model folder.",
        "모델 폴더": "Model folder",
        "모델 내려놓기": "Unload model",
        "대화 연결": "Connect chat",
        "모델 실행": "Start model",
        "로그 열기": "Open logs",
        "모델 준비 완료 · 대화에 연결할 수 있습니다.": "Model ready · you can connect to chat.",
        "모델을 준비하고 있습니다. 연결 가능 여부를 자동 확인합니다.": "Preparing the model. Checking server readiness automatically.",
        "모델은 사용자가 준비한 로컬 폴더에서 불러옵니다.": "Models load from local folders you have prepared.",
        "실행 중인 서버 찾기": "Find running servers",
        "LM Studio · Ollama · H3 서버의 로컬 연결을 확인합니다.": "Checks local connections for LM Studio, Ollama and H3 servers.",
        "검색 중…": "Searching…",
        "내 Mac에서 찾기": "Find on my Mac",
        "연결": "Connect",
        "모델이 준비된 서버를 실행한 뒤 찾기를 눌러주세요.": "Start a server with a model ready, then search.",
        "기존 로컬 서버 연결": "Connect an existing local server",
        "연결 확인": "Check connection",
        "{0}개 모델 연결됨": "{0} models connected",
        "대화로 이동": "Go to chat",
        "실행 도구 및 연결 범위": "Runtimes and connection scope",
        "앱은 루프백 주소에만 연결합니다. 외부 서버의 클라우드 연동 여부는 해당 도구의 설정에서 확인하세요.": "This connection accepts loopback addresses only. Check your runtime's settings for any cloud integrations.",
        "데이터와 작업 기록": "Data and job records",
        "대화와 입력 초안은 이 Mac에 자동 저장됩니다. 새 대화를 시작하면 기존 대화를 비웁니다. 생성 작업의 입력·설정·로그·결과도 Mac에 보관됩니다.": "Conversations and drafts are saved on this Mac. Starting a new chat clears the current conversation. Generation inputs, settings, logs and outputs also stay on your Mac.",
        "로컬 작업 폴더 열기": "Open local jobs folder",
        "답변 준비 중…": "Preparing response…",
        "함께 생각해볼까요?": "Shall we think it through?",
        "새 대화": "New chat",
        "콘텐츠 생성이 끝나면 대화를 이어갈 수 있습니다.": "Continue chatting when content generation finishes.",
        "모델을 연결하면 저장된 대화를 이어갈 수 있습니다.": "Connect a model to continue your saved conversation.",
        "모델 연결하기": "Connect model",
        "대화 모델": "Chat model",
        "어떤 일부터 시작할까요?": "What would you like to start with?",
        "오늘 할 일을 우선순위에 따라 정리해줘": "Help me prioritize today's tasks",
        "새로운 서비스 아이디어를 함께 구체화해줘": "Help me develop a new service idea",
        "다음 문장을 더 명확하고 자연스럽게 다듬어줘": "Make the following text clearer and more natural",
        "나": "You",
        "내용 복사": "Copy content",
        "H3 · 응답 중": "H3 · Responding",
        "중단된 부분 응답": "Interrupted partial response",
        "첫 응답 %.2f초 · 연결 및 서버 대기 포함": "First response %.2fs · includes connection and server wait",
        "⌘ Return으로 보내기 · 답변은 확인이 필요합니다.": "⌘ Return to send · Review AI responses.",
        "보내기": "Send",
        "현재 대화를 지우고 새로 시작할까요?": "Clear this conversation and start again?",
        "새 대화 시작": "Start new chat",
        "만든 것들을 한곳에": "Everything you create, together",
        "새로고침": "Refresh",
        "최신 작업부터 확인하고, 원본 결과와 실행 기록을 다시 열어보세요.": "Find recent jobs and reopen original outputs and execution records.",
        "아직 저장된 작업이 없습니다": "No saved jobs yet",
        "음성·이미지·영상을 만들면 이곳에 기록됩니다.": "Speech, image and video jobs will appear here.",
        "열기": "Open",
        "서버가 종료되었습니다 ({0}). 로그를 확인하세요.": "Server exited ({0}). Check the logs.",
        "음성 언어": "Speech language",
        "영어": "English",
        "대기": "Waiting",
        "로컬 AI": "Local AI"
    ]
}
func L(_ key: String, _ arguments: String...) -> String {
    var value = AppLanguage.code == "en" ? (AppLanguage.english[key] ?? key) : key
    // Replace all placeholders in one pass so user content cannot be interpreted as a placeholder.
    let regex = try! NSRegularExpression(pattern: #"\{([0-9]+)\}"#)
    for match in regex.matches(in: value, range: NSRange(value.startIndex..., in: value)).reversed() {
        guard let range = Range(match.range(at: 1), in: value), let index = Int(value[range]), arguments.indices.contains(index), let full = Range(match.range, in: value) else { continue }
        value.replaceSubrange(full, with: arguments[index])
    }
    return value
}
